SET MARKUP JSON ON
SELECT refnum, Mask_pan, amount, OMNI_LOG_DT_UTC
FROM oasis77.shclog 
WHERE refnum IN ('425611726410')
AND acquirer LIKE '%000054%'
ORDER BY OMNI_LOG_DT_UTC DESC;
SET MARKUP JSON OFF